# Dependencies
markdown:               redcarpet
highlighter:            pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:              pretty
relative_permalinks:    true

# Site settings
title:                  Sergey's blog
email:                  timanin@gmail.com
description:            My musings and ponderings about devops and technology.
baseurl:                /
url:                    http://blog.sergeytimanin.com
timezone:               Europe/London
paginate:               5

# About/contact
author:
    name:               Sergey Timanin
    email:              timanin@gmail.com
    url:                http://blog.sergeytimanin.com
    twitter:            sergeytimanin
    github:             timanin
    linkedin:           timanin
    email_md5:          cc744b30de91c8ce928a083cad416441

# Custom vars
version:                0.0.1
