# Site settings
title: Sergey's blog
email: timanin@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My musings and ponderings about devops and technology.
baseurl: ""
url: "https://blog.sergeytimanin.com"
twitter_username: sergeytimanin
github_username:  timanin
timezone: Europe/London

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# defaults
defaults:
  -
    scope:
      path: "."
      type: "posts"
    values:
      layout: "project"
      author: "Sergey Timanin"
      category: "project"
